### ISSUE TITLE
application broken if params validation fails

### ISSUE THREAD

**Issue by darky** [tiaod/moleculer-io#10]
If using params validation: https://moleculer.services/docs/0.13/validating.html
and call of action invalid, app broken with error:
`Error action "io.call" with error: ValidationError: Parameters validation error!`

Helps only restart

**Comment by tiaod** [comment]
I tested no problems found. Could you give me your source code to see?
![image](https://user-images.githubusercontent.com/7500825/52892283-faf51a80-31cb-11e9-82f9-eaef67ddc06e.png)

**Comment by darky** [comment]
Hmm, ok, I discover it more in details..
Maybe error on another side.

**Comment by darky** [comment]
I discover problem. It strange, but it broken with winston logger:
https://moleculer.services/docs/0.13/logging.html#Winston
:smile:

**Comment by tiaod** [comment]
I write an example with winston logger, and I didn't found any problem
![image](https://user-images.githubusercontent.com/7500825/52956891-62c58400-33cb-11e9-83e0-8d021745d128.png)


Source code:
https://github.com/tiaod/moleculer-io/tree/winston-logger/examples/winston-logger

**Comment by darky** [comment]
Ok, I try to discover it more deeply later
My project so big, hard to expose error clearly

**Comment by darky** [comment]
Ok, I finally detect problem.
It broken with my middlewares `localAction`, which throw error.
I fix it by placing:

```
if (action.name === 'io.call') {
  return next(ctx);
}
```

on each `localAction` middleware
