### ISSUE TITLE
remove babel build

### ISSUE THREAD

**Issue by darky** [tiaod/moleculer-io#11]
node.js 6 nearly of end of life.
Since node.js 8 you can relax on `async/await`

**Comment by tiaod** [comment]
But moleculer  itself is written in ES2015. The minimum version of Node.js is v6.x.x.
https://github.com/moleculerjs/moleculer/blob/master/package.json#L98
![image](https://user-images.githubusercontent.com/7500825/52901577-52cd6900-3240-11e9-8ef6-4f3f0fb3d929.png)

**Comment by tiaod** [comment]
I modify the .babelrc and set `targets.node` to "current", I think this will be fine for future versions.
