### ISSUE TITLE
How can I access to currenct context in socketAuthorize method

### ISSUE THREAD

**Issue by cantecim** [tiaod/moleculer-io#15]
Hello, I have to check token with my user service in order to validate it.

So, I need to access current context in socketAuthorize method.

Since it is a socket.io middleware and there is no context when it is defined I couldn't able to find a workaround.

Could you suggest something?

**Comment by tiaod** [comment]
Do you want to call action in middlewares? `socket.$service` is pointed to service instance, you can call actions via `socket.$service.broker.call`. Here is an example: 
```js
async socketAuthorize(socket, eventHandler){
      let accessToken = socket.handshake.query.token
      if (accessToken) {
        // valid credential, return the user
        try{
          let user = await socket.$service.broker.call('account.checkToken', {
            token: accessToken
          })
          return { id: 1, detail: "You are authorized using token.", name: "John Doe" }
        }catch(err){
          // invalid credentials
          throw new Error('invalid token!')
        }
      } else {
      // anonymous user
        return
      }
    }
```

**Comment by cantecim** [comment]
Aha, I miss that! Thank you that what I want. I would like to add this example to README.md 👍
