### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by icebob** [tiaod/moleculer-io#2]
Hi @tiaod,

when will you make a new release? I'm trying to use it with moleculer-web but the last release doesn't contain this line: https://github.com/tiaod/moleculer-io/blob/master/src/index.js#L40

Thanks!

**Comment by icebob** [comment]
The latest version on NPM is 0.12.1

```
{ name: 'moleculer-io',
  'dist-tags': { latest: '0.12.1' },
```

**Comment by tiaod** [comment]
Oh, I am so sorry that I had forgot to release the latest version. :sweat_smile:
Thanks for reminding.
