### ISSUE TITLE
Socket.io closing issue

### ISSUE THREAD

**Issue by icebob** [tiaod/moleculer-io#20]
Hi, 
There is some issue when you close the socket.io server in the `stopped` lifecycle handler.
Try to start an example without npm, just with naked node:
`node examples/full/index.js`
If started, open the browser, client will connect and press **once** CTRL+C.
The ServiceBroker can't stop.

If you start debugging you will see that the lib/index.js:105 callback doesn't triggered and the Promise will never be fulfilled. 
![image](https://user-images.githubusercontent.com/306521/60402009-b752ea00-9b89-11e9-83d4-8f9348f6f4c8.png)

Could you fix it? I don't know what is the root of the problem.

**Comment by icebob** [comment]
I found the answer in socket.io docs. It says: `Closes the socket.io server. The callback argument is optional and will be called when all connections are closed.` 
So it won't call the callback while there are live connections.

**Comment by tiaod** [comment]
@icebob I know this issue and I don't konw how to fix it. I didn't find a way to force close `socket.io` server.

**Comment by icebob** [comment]
I think you should not wait for the callback because if you call the close, the server won't accept new connections and live connections will be closed when the process exited.

**Comment by tiaod** [comment]
@icebob You are right! 👍 How did I miss this simple way?

**Comment by icebob** [comment]
Great :)
