### ISSUE TITLE
Overwrite strategy

### ISSUE THREAD

**Issue by lehno** [tiaod/moleculer-io#26]
With version 0.14 now its possible to overwrite strategy like round robin or shard.
For websockets, sometimes the context of a connections is in the service being called, if you have multiple services, you need to keep the user going to the same service using Shard Strategy, so context (example: recording an audio) will be available.
Will it work out of the box or does it need modification on the code?

**Comment by lehno** [comment]
https://github.com/moleculerjs/moleculer/blob/next/CHANGELOG.md

**Comment by lehno** [comment]
I see that moleculer 0.14 using shard wont be compatible with moleculer.io, I wont be able to use moleculer-io until its compatible with custom strategies. Let me know if you have plans of implementing this feature

**Comment by lehno** [comment]
I had a chat with icebob and the shard setting goes to the called service, so io is fine, only one thing, version 0.14 has findNextActionEndpoint second param the context, so it should be fixed anyway

**Comment by lehno** [comment]
Was this change published to npm?

**Comment by tiaod** [comment]
> Was this change published to npm?

yes
