### ISSUE TITLE
Access to SocketIO Object in services

### ISSUE THREAD

**Issue by thiagomagro** [tiaod/moleculer-io#6]
Hello guys.
Can we have access to the socket io object inside services?
If I need to, for example, check the clients inside a room (io.sockets.clients('room')), whats the correct way of doing this?

Thanks!

**Comment by tiaod** [comment]
Services are running on individual nodes, you can't access the io object from other service (Which may run in different node!)
![image](https://user-images.githubusercontent.com/7500825/51665523-ea9bb680-1ff6-11e9-9079-f55c53863c14.png)

So the best way to access the io object is in your socket.io service: 

```js
const ioService = broker.createService({
  name: 'io',
  mixins: [SocketIOService],
  settings: {
    port: 3000
  },
  actions: { // Write your actions here!
    checkClientsInsideRoom:{
      params:{
        namespaces: 'string',
        room: 'string'
      },
      handler(ctx){
        return new Promise(function(resolve, reject) {
          io.of(ctx.params.namespaces).to(ctx.params.room).clients((err, clients)=>{
            if(err){
              return reject(err)
            }
            resolve(clients)
          })
        })
      }
    }
  }
})
```

**Comment by thiagomagro** [comment]
Great info @tiaod.
Thanks for the quick reply.
