### ISSUE TITLE
Error after upgrading to 1.0.0

### ISSUE THREAD

**Issue by flaviocordova** [tiaod/moleculer-io#8]
After upgrading to 1.0.0, I'm having this problem:

ReferenceError: debug is not defined
    at <dir>/moleculer-io/lib/index.js:230:11

```javascript
        return _asyncToGenerator(function* () {
          debug('brocast: ', ctx.params);
          let namespace = _this2.io;
```

Shouldn't it be ```_this2.logger.debug('broadcast: ', ctx.params);```

**Comment by tiaod** [comment]
Sorry, I had forgot to remove the `debug` lib in brocast action 😅 

Fixed at v1.0.1
